import React from "react";

const sizeClasses = {
  txtPoppinsSemiBold50WhiteA700: "font-poppins font-semibold",
  txtPoppinsSemiBold123: "font-poppins font-semibold",
  txtInterRegular20: "font-inter font-normal",
  txtPoppinsMediumItalic78: "font-medium font-poppins italic",
  txtPoppinsSemiBold2057: "font-poppins font-semibold",
  txtPoppinsMedium1304: "font-medium font-poppins",
  txtPoppinsMedium16Black90001: "font-medium font-poppins",
  txtPoppinsRegular26: "font-normal font-poppins",
  txtJostRomanMedium16WhiteA700: "font-jost font-medium",
  txtPoppinsSemiBold14: "font-poppins font-semibold",
  txtPoppinsSemiBold16Gray700: "font-poppins font-semibold",
  txtPoppinsSemiBold16: "font-poppins font-semibold",
  txtPoppinsSemiBold12: "font-poppins font-semibold",
  txtArialBoldMT20: "font-arial font-bold",
  txtInterRegular24: "font-inter font-normal",
  txtInterRegular8: "font-inter font-normal",
  txtPoppinsSemiBold18: "font-poppins font-semibold",
  txtPoppinsRegular14WhiteA700: "font-normal font-poppins",
  txtPoppinsBlack16: "font-black font-poppins",
  txtPoppinsRegular18: "font-normal font-poppins",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtInterMedium3294: "font-inter font-medium",
  txtPoppinsRegular2364: "font-normal font-poppins",
  txtPoppinsRegular15: "font-normal font-poppins",
  txtPoppinsRegular16: "font-normal font-poppins",
  txtPoppinsMedium931: "font-medium font-poppins",
  txtPoppinsRegular14Bluegray900: "font-normal font-poppins",
  txtPoppinsSemiBold24: "font-poppins font-semibold",
  txtPoppinsRegular22: "font-normal font-poppins",
  txtPoppinsSemiBold26: "font-poppins font-semibold",
  txtPoppinsRegular23: "font-normal font-poppins",
  txtPoppinsMedium30Black900: "font-medium font-poppins",
  txtPoppinsRegular24: "font-normal font-poppins",
  txtPoppinsSemiBold20: "font-poppins font-semibold",
  txtPoppinsSemiBold1491: "font-poppins font-semibold",
  txtPoppinsRegular20: "font-normal font-poppins",
  txtPoppinsSemiBold2057Gray700: "font-poppins font-semibold",
  txtPoppinsSemiBold20Black90001: "font-poppins font-semibold",
  txtPoppinsSemiBold40WhiteA700: "font-poppins font-semibold",
  txtPoppinsSemiBold32Green700: "font-poppins font-semibold",
  txtPoppinsSemiBold16RedA700: "font-poppins font-semibold",
  txtPoppinsBlack24: "font-black font-poppins",
  txtPoppinsMedium923: "font-medium font-poppins",
  txtPoppinsSemiBold30: "font-poppins font-semibold",
  txtPoppinsMedium1603: "font-medium font-poppins",
  txtPoppinsSemiBold32: "font-poppins font-semibold",
  txtPoppinsSemiBold16Gray50001: "font-poppins font-semibold",
  txtPoppinsSemiBold20Black900: "font-poppins font-semibold",
  txtPoppinsSemiBold12WhiteA700: "font-poppins font-semibold",
  txtPoppinsRegular18Bluegray900: "font-normal font-poppins",
  txtPoppinsMedium2364: "font-medium font-poppins",
  txtPoppinsMedium1671: "font-medium font-poppins",
  txtArialBoldMT24: "font-arial font-bold",
  txtInterMedium32: "font-inter font-medium",
  txtPoppinsSemiBold40: "font-poppins font-semibold",
  txtPoppinsSemiBold16Black90001: "font-poppins font-semibold",
  txtInterMedium36: "font-inter font-medium",
  txtPoppinsSemiBold16Green700: "font-poppins font-semibold",
  txtPoppinsMedium40: "font-medium font-poppins",
  txtPoppinsMedium13RedA700: "font-medium font-poppins",
  txtPoppinsMedium13Black90001: "font-medium font-poppins",
  txtPoppinsRegular978: "font-normal font-poppins",
  txtPoppinsMedium16Gray700: "font-medium font-poppins",
  txtPoppinsSemiBold32Black90001: "font-poppins font-semibold",
  txtPoppinsMedium13Gray900: "font-medium font-poppins",
  txtPoppinsSemiBold50: "font-poppins font-semibold",
  txtPoppinsSemiBold20Green700: "font-poppins font-semibold",
  txtInterMedium24: "font-inter font-medium",
  txtPoppinsRegular16Bluegray900: "font-normal font-poppins",
  txtPoppinsRegular20Bluegray900: "font-normal font-poppins",
  txtPoppinsSemiBold32Black900: "font-poppins font-semibold",
  txtPoppinsRegular1003: "font-normal font-poppins",
  txtPoppinsMedium106: "font-medium font-poppins",
  txtPoppinsRegular16WhiteA700: "font-normal font-poppins",
  txtPoppinsSemiBold16Gray900: "font-poppins font-semibold",
  txtPoppinsRegular1999: "font-normal font-poppins",
  txtPoppinsMedium30: "font-medium font-poppins",
  txtPoppinsRegular20WhiteA700: "font-normal font-poppins",
  txtPoppinsBold2301: "font-bold font-poppins",
  txtPoppinsMedium13Gray50001: "font-medium font-poppins",
  txtPoppinsSemiBold16IndigoA200: "font-poppins font-semibold",
  txtJostRomanMedium16: "font-jost font-medium",
  txtPoppinsMedium1211: "font-medium font-poppins",
  txtPoppinsMedium20Bluegray900: "font-medium font-poppins",
  txtPoppinsMedium13Lightblue900: "font-medium font-poppins",
  txtPoppinsSemiBold20Lightblue900: "font-poppins font-semibold",
  txtPoppinsMedium1214: "font-medium font-poppins",
  txtPoppinsRegular26Black900: "font-normal font-poppins",
  txtPoppinsRegular1076: "font-normal font-poppins",
  txtPoppinsMedium24: "font-medium font-poppins",
  txtPoppinsMedium30Bluegray100: "font-medium font-poppins",
  txtPoppinsMedium1671Green700: "font-medium font-poppins",
  txtPoppinsRegular14Gray900: "font-normal font-poppins",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtInterMedium20: "font-inter font-medium",
  txtPoppinsRegular14Gray500: "font-normal font-poppins",
  txtPoppinsMedium24WhiteA700: "font-medium font-poppins",
  txtPoppinsRegular18Gray900: "font-normal font-poppins",
  txtPoppinsMedium13WhiteA700: "font-medium font-poppins",
  txtPoppinsMedium14Red400: "font-medium font-poppins",
  txtPoppinsRegular911: "font-normal font-poppins",
  txtOutfitSemiBold32: "font-outfit font-semibold",
  txtPoppinsSemiBold16WhiteA700: "font-poppins font-semibold",
  txtPoppinsMedium26: "font-medium font-poppins",
  txtPoppinsSemiBold1305: "font-poppins font-semibold",
  txtPoppinsSemiBold1491Gray700: "font-poppins font-semibold",
  txtPoppinsMedium20Gray900: "font-medium font-poppins",
  txtPoppinsRegular2196: "font-normal font-poppins",
  txtPoppinsMedium24Gray900: "font-medium font-poppins",
  txtPoppinsMediumItalic14: "font-medium font-poppins italic",
  txtPoppinsSemiBold1146: "font-poppins font-semibold",
  txtPoppinsSemiBold1543: "font-poppins font-semibold",
  txtOpenSansBold20: "font-bold font-opensans",
  txtPoppinsSemiBold70: "font-poppins font-semibold",
  txtPoppinsSemiBold18WhiteA700: "font-poppins font-semibold",
  txtPoppinsMedium13: "font-medium font-poppins",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtPoppinsMedium12: "font-medium font-poppins",
  txtPoppinsBold3616: "font-bold font-poppins",
  txtPoppinsMedium18: "font-medium font-poppins",
  txtPoppinsMedium16: "font-medium font-poppins",
  txtPoppinsMedium1603Gray900: "font-medium font-poppins",
  txtPoppinsMedium13Green700: "font-medium font-poppins",
  txtPoppinsMedium1115: "font-medium font-poppins",
  txtPoppinsSemiBold20Gray700: "font-poppins font-semibold",
  txtPoppinsBold20: "font-bold font-poppins",
  txtPoppinsMedium16WhiteA700: "font-medium font-poppins",
  txtPoppinsBold24: "font-bold font-poppins",
  txtPoppinsSemiBold16Lightblue900: "font-poppins font-semibold",
  txtPoppinsSemiBold1146Gray700: "font-poppins font-semibold",
  txtInterRegular2138: "font-inter font-normal",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
